### ISSUE TITLE
Back button doesn't work properly

### ISSUE THREAD

**Issue by Kyle772** [alexzaganelli/strapi-plugin-email-designer#100]
### Describe the bug
It refreshes whatever page you're on

### Steps to reproduce the behavior

1. Go to edit a template
3. Click on go back (to the template navigation screen)

### Expected behavior

Always goes to the template navigation

**Comment by SalahAdDin** [comment]
> ## Bug report
> ### Describe the bug
> 
> It refreshes whatever page you're on
> ### Steps to reproduce the behavior
> 
>     1. Go to edit a template
> 
>     2. Click on go back (to the template navigation screen)
> 
>     3. See error
> 
> 
> ### Expected behavior
> 
> Always goes to the template navigation

Yeah, it is right, I can show a video from it:
Uploading Screen Recording 2022-10-09 at 17.35.14.mov…

**Comment by alexzaganelli** [comment]
Fixed
