### ISSUE TITLE
Can't change shipper name 

### ISSUE THREAD

**Issue by slipiduche** [alexzaganelli/strapi-plugin-email-designer#101]
HI, how can I change shipper name in custom templates?

**Comment by BayBreezy** [comment]
Hey @slipiduche ,

You can check the `Email templates` settings for the two email created by Strapi in every project http://localhost:1337/admin/settings/users-permissions/email-templates

Clicking on the `Reset password` or `Email address confirmation` template will give the option to change the Shipper email

Ensure that the email config is done properly in your `config/plugins.{js|ts}` file:

```js
 // Email config
  email: {
    config: {
      provider: "nodemailer",
      providerOptions: {
        host: env("SMTP_HOST"),
        port: env("SMTP_PORT"),
        auth: {
          user: env("SMTP_USERNAME"),
          pass: env("SMTP_PASSWORD"),
        },
      },
      settings: {
        defaultFrom: `<${env("SMTP_USERNAME")}>`,
        defaultReplyTo: env("SMTP_USERNAME"),
      },
    },
  },
```
