### ISSUE TITLE
plugin installed but has error

### ISSUE THREAD

**Issue by sharkfin009** [alexzaganelli/strapi-plugin-email-designer#103]
## Bug report
I have an unresponsive plugin, and an error in the console

### Steps to reproduce the behavior

1 install plugin
go to menu item
try to use plugin

### Expected behavior

To have a responsive application
### Code snippets
js console error:

[request].0ccf0344.chunk.js:248 Refused to load the script 'https://editor.unlayer.com/embed.js?2' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### Describe the bug

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version:
- Plugin version:
- Database:
- Operating system:

**Comment by BayBreezy** [comment]
Hey,

You may need to configure your middleware in Strapi to get rid of this error. It was also stated in the docs.

// ...
- "strapi::security",
+ {
+     name: "strapi::security",
+     config: {
+       contentSecurityPolicy: {
+         directives: {
+           "script-src": ["'self'", "editor.unlayer.com"],
+           "frame-src": ["'self'", "editor.unlayer.com"],
+           "img-src": [
+             "'self'",
+             "data:",
+             "cdn.jsdelivr.net",
+             "strapi.io",
+             "s3.amazonaws.com",
+           ],
+         },
+       },
+     },
+   },
// ...

Check hee for details [Add Unlayer to CSP](https://market.strapi.io/plugins/strapi-plugin-email-designer)

**Comment by beltebelt** [comment]
Seem to be having similar issue, even after adding the middleware config
```
Refused to load the script 'https://editor.unlayer.com/embed.js?2' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
```javascript
export default [
  'strapi::logger',
  'strapi::errors',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        directives: {
          "script-src": ["'self'", "editor.unlayer.com"],
          "frame-src": ["'self'", "editor.unlayer.com"],
          "img-src": [
            "'self'",
            "data:",
            "cdn.jsdelivr.net",
            "strapi.io",
            "s3.amazonaws.com",
          ],
        },
      },
    },
  },
];

```
