### ISSUE TITLE
Support for Node 18

### ISSUE THREAD

**Issue by marcowuethrich** [alexzaganelli/strapi-plugin-email-designer#104]
### Summary

It would be nice if we could get the plugin working on Node 18. 

### Why is it needed?

To develop local frontend applications on node 18 with a strapi CMS running parallel within the same node version. For a better developer experience.

Strapi supports already Node 18:
```
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  }
```

### Suggested solution(s)

Increasing the engines in the package.json and test the plugin before publishing.

From:
```
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
```
To the same as Strapi:
```
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  }
```

### Related issue(s)/PR(s)

TBD

**Comment by paulVu** [comment]
I'm have a same problem with this one. 
Do you know: how to uninstall this plugin, I can't deploy to production. 
thanks
