### ISSUE TITLE
Can't populate email templates in api when used as a relation

### ISSUE THREAD

**Issue by darkcherrycreative** [alexzaganelli/strapi-plugin-email-designer#107]
I've got an api endpoint which has a oneToOne relationship with email templates 

"Template": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::email-designer.email-template"
    }

This works fine from the admin UI and i can select from the templates list, however when using the Strapi 3 version i also used to get the email template data in the REST data, there seems to be no way to populate this anymore. Data from the related field is simply not returned.

Is this by design or a bug?

**Comment by alexzaganelli** [comment]
Hi @darkcherrycreative 

Shouldn't be related to the plugin but to the Strapi core.
