### ISSUE TITLE
Where to add email sending logic?

### ISSUE THREAD

**Issue by Chaitu17** [alexzaganelli/strapi-plugin-email-designer#109]
### Discussed in https://github.com/alexzaganelli/strapi-plugin-email-designer/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **Chaitu17** November 21, 2022</sup>
After creating the template design, in which file should we add the email sending logic in the repository(knowing filePath and function can be really helpful)? Can someone give a detailed explanation for the issue? (currently using the latest version of strapi as per the date v4.5.1). A step by step guide can help.</div>

**Comment by Kyle772** [comment]
You can add the email sending logic anywhere in your strapi project. I send during a lifecycle most of the time but you could put it in a service, a controller, a cronjob, literally anywhere. Check the readme for examples.
