### ISSUE TITLE
Error when build a project with Strapi v4.5.5 - fortawesome library

### ISSUE THREAD

**Issue by eucciferri** [alexzaganelli/strapi-plugin-email-designer#114]
## Bug report
Error when building the project with the latest version of Strapi v4.5.5.

### Describe the bug
When building a project, it throws an error related to the fortawesome library that the Email Designer plugin uses.

### Steps to reproduce the behavior

1. Update Strapi to 4.5.5
2. Execute npm run build
3. See error

### Expected behavior
A successful build

### Screenshots
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/38674416/209889733-f2790ca8-fe42-4bd6-842f-caa683bb57d5.png">

### Code snippets
N/A

### System

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.5.5
- Plugin version: 2.1.1
- Database: postgresql
- Operating system: macOS Ventura

### Additional context
N/A

**Comment by alexzaganelli** [comment]
Fixed in [2.1.2](https://github.com/alexzaganelli/strapi-plugin-email-designer/commit/65cd882d1600721e629116a01bedc8d85a557d53)
