### ISSUE TITLE
Template keeps disappearing.

### ISSUE THREAD

**Issue by MoeedthePessimist** [alexzaganelli/strapi-plugin-email-designer#127]
### Describe the bug

Store templates keeps disappearing after a while, either after a server restart or server error.

### Steps to reproduce the behavior

1. Go to email-designer plugin on strapi admin dashboard.
2. Click new template.
3. Create a new template.
4. Store the template.
5. Template is visible and email is sent programmatically.
6. Restart the server.
7. Go to email-designer plugin on strapi admin dashboard.
8. Email template is not there anymore.

### Expected behavior

Email template should be there. 

### Screenshots

before server restart.
![image](https://github.com/alexzaganelli/strapi-plugin-email-designer/assets/63580699/7bfac35e-8c24-4e5f-bdb8-fcfcf1359f97)

after server restart
![image](https://github.com/alexzaganelli/strapi-plugin-email-designer/assets/63580699/447ce61c-bd96-4740-90a1-eddcbca133a2)

### System

- Node.js version: v 18.17.0
- NPM version: 9.6.7
- Yarn version: 1.22.19
- Strapi version: v4.11.7
- Plugin version: "^2.1.2"
- Database: postgres
- Operating system: windows 11 home edition 64bit

### Additional context

Sometimes I get an error related to database that this object doesn't exists, even after the template is present.

**Comment by edward-urbanik** [comment]
same here

**Comment by RingoMckraken** [comment]
I am also experiencing this. Its as if the table gets dropped and re-added or truncated. This is very frustrating.

**Comment by alexzaganelli** [comment]
This issue should be fixed w/ the new Strapi's UI package.
