### ISSUE TITLE
How do you add authentification for cypress

### ISSUE THREAD

**Issue by bidoubiwa** [alexzaganelli/strapi-plugin-email-designer#13]
Hello @alexzaganelli 
I was testing out the code of your great plugin. I tried running the tests but they stopped at the login. Is there a way you can add authentification credentials (name and password) in an accessible way to make login automatic?

**Comment by alexzaganelli** [comment]
Hi @bidoubiwa thank you for your interesting. I've added the login flow to the test. Feel free to pull and give it a try.

I hope to have helped you. Let me know.
