### ISSUE TITLE
export 'NotFound' (inported as 'NotFOund' was not found in '@strapi/helper-plugin'

### ISSUE THREAD

**Issue by hailwood** [alexzaganelli/strapi-plugin-email-designer#130]
## Bug report
![image](https://github.com/alexzaganelli/strapi-plugin-email-designer/assets/709773/68da25f7-fe4c-4369-9513-58fe3147c78e)

### Steps to reproduce the behavior

run `strapi develop --watch-admin`

### Expected behavior

No errors

### System

- Node.js version: tried node 12 - node 20
- NPM version: ""
- Strapi version: 4.12.5
- Plugin version: 2.1.2
- Database:
- Operating system:

**Comment by rrubio** [comment]
@yanicklandry  should this issue be closed?
