### ISSUE TITLE
Email designer is broken with strapi 4.19.0

### ISSUE THREAD

**Issue by guerillacodester** [alexzaganelli/strapi-plugin-email-designer#140]
The designer is broken with strapi version 4.19.0

1) install the plugin as per documentation
2) click the Email designer tab
3) a blank white screen appears with no ability to edit or save.
4) reverting to strapi version 4.17.0 fixes the issue.

**Comment by guerillacodester** [comment]
Seems to be a strapi issue, since it works again with the recent strapi ver 4.19.1

**Comment by kubarazny** [comment]
> Seems to be a strapi issue, since it works again with the recent strapi ver 4.19.1

I have still this issue on 4.19.1

`Refused to load https://editor.unlayer.com/embed.js?2 because it does not appear in the script-src directive of the Content Security Policy.`

I need to add `editor.unlayer.com/embed.js` to the `script-src` directive

**Comment by LatinCoder18** [comment]
> > Seems to be a strapi issue, since it works again with the recent strapi ver 4.19.1
> 
> I have still this issue on 4.19.1
> 
> `Refused to load https://editor.unlayer.com/embed.js?2 because it does not appear in the script-src directive of the Content Security Policy.`
> 
> I need to add `editor.unlayer.com/embed.js` to the `script-src` directive

Hi, can you share an example of how you do that ?

 'script-src': ["'self'", "'unsafe-inline'",'editor.unlayer.com/embed.js','editor.unlayer.com/embed.js?2='],
 
 
![imagen](https://github.com/alexzaganelli/strapi-plugin-email-designer/assets/40668572/2c59b6d7-d2d1-49fc-bd45-ba3abd3dc85e)

 
I used that but did not work.

Thanks !

**Comment by kubarazny** [comment]
> > > Seems to be a strapi issue, since it works again with the recent strapi ver 4.19.1
> > 
> > 
> > I have still this issue on 4.19.1
> > `Refused to load https://editor.unlayer.com/embed.js?2 because it does not appear in the script-src directive of the Content Security Policy.`
> > I need to add `editor.unlayer.com/embed.js` to the `script-src` directive
> 
> Hi, can you share an example of how you do that ?
> 
> 'script-src': ["'self'", "'unsafe-inline'",'editor.unlayer.com/embed.js','editor.unlayer.com/embed.js?2='],
> 
> ![imagen](https://private-user-images.githubusercontent.com/40668572/303117135-2c59b6d7-d2d1-49fc-bd45-ba3abd3dc85e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzU1OTAsIm5iZiI6MTcwNzMzNTI5MCwicGF0aCI6Ii80MDY2ODU3Mi8zMDMxMTcxMzUtMmM1OWI2ZDctZDJkMS00OWZjLWJkNDUtYmEzYWJkM2RjODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE5NDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYjM3Y2VjODFlNTBhMzk4M2U5OTUzYWFhNDNkZDNiY2NiYWI1OTAzMThkZTgzZjU0NjE5ZWNmM2U0ZDAyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.meEy3hZJiF0cyll_ZhmMsLSLjRyf6f7PIOVQhRAPQME)
> 
> I used that but did not work.
> 
> Thanks !

Try this:

`contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com', "cdn.jsdelivr.net", "strapi.io", "s3.amazonaws.com"],
          'media-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com'],
          "script-src": ["'self'", "editor.unlayer.com", "editor.unlayer.com/embed.js"],
          "frame-src": ["'self'", "editor.unlayer.com"],
        },
      },`

**Comment by guerillacodester** [comment]
I did nothing different. Just deleted the node_modules, .strapi and all dist folders, and upgraded strapi to the latest via yarn.Now it works.

**Comment by LatinCoder18** [comment]
> > > > Seems to be a strapi issue, since it works again with the recent strapi ver 4.19.1
> > > 
> > > 
> > > I have still this issue on 4.19.1
> > > `Refused to load https://editor.unlayer.com/embed.js?2 because it does not appear in the script-src directive of the Content Security Policy.`
> > > I need to add `editor.unlayer.com/embed.js` to the `script-src` directive
> > 
> > 
> > Hi, can you share an example of how you do that ?
> > 'script-src': ["'self'", "'unsafe-inline'",'editor.unlayer.com/embed.js','editor.unlayer.com/embed.js?2='],
> > ![imagen](https://private-user-images.githubusercontent.com/40668572/303117135-2c59b6d7-d2d1-49fc-bd45-ba3abd3dc85e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzU1OTAsIm5iZiI6MTcwNzMzNTI5MCwicGF0aCI6Ii80MDY2ODU3Mi8zMDMxMTcxMzUtMmM1OWI2ZDctZDJkMS00OWZjLWJkNDUtYmEzYWJkM2RjODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE5NDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYjM3Y2VjODFlNTBhMzk4M2U5OTUzYWFhNDNkZDNiY2NiYWI1OTAzMThkZTgzZjU0NjE5ZWNmM2U0ZDAyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.meEy3hZJiF0cyll_ZhmMsLSLjRyf6f7PIOVQhRAPQME)
> > I used that but did not work.
> > Thanks !
> 
> Try this:
> 
> `contentSecurityPolicy: { useDefaults: true, directives: { 'connect-src': ["'self'", 'https:'], 'img-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com', "cdn.jsdelivr.net", "strapi.io", "s3.amazonaws.com"], 'media-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com'], "script-src": ["'self'", "editor.unlayer.com", "editor.unlayer.com/embed.js"], "frame-src": ["'self'", "editor.unlayer.com"], }, },`

@kubarazny  Thanks, that works for me !

**Comment by panosru** [comment]
That indeed fixed the issue, but now I cannot see the icons of plugins in marketplace, any suggestions how can I fix that? I'm very new to strapi (like today) so I'm sorry for the n00bish question.

**UPDATE:**
Adding `"market-assets.strapi.io"` to `img-src` fixed it.
