### ISSUE TITLE
⚠️ Update / Fork with breaking changes

### ISSUE THREAD

**Issue by creazy231** [alexzaganelli/strapi-plugin-email-designer#16]
Hello Alexandre. First of all thank you for the possibility to design email templates in Strapi.
I tried the plugin, but I encountered several errors in the latest version of Strapi with Lodash templating.

I have forked your project and made some adjustments. If you feel like it, you can check it out. The README should be mostly updated as well. Please note, that these adjustments **include breaking changes**.

Link: https://github.com/creazy231/strapi-plugin-email-designer

I would be really happy to make PRs in the future as well.

Features my fork includes:

- Automatically generate Text from HTML if there is no given Text Template.
- Use official Lodash Templating format. Example: `<%= variable %>`
- Use official Strapi syntax to send emails
- Updated Tests to switch language to english

All changes I've made are documented in this commit: https://github.com/creazy231/strapi-plugin-email-designer/commit/599377463dd89532bbca5ace4f5a7a72b3bdeb59

**Comment by alexzaganelli** [comment]
Hi @creazy231, first of thank you so much for your contribution and for your great work 🙏🏼

Honestly I think would be great also to leave for a while the old methods (w/ a deprecation message) then I'll happy to merge instantly. Only I need is to find some time to do that.

Thank you again.

@all-contributors please add @creazy231 for code, design and ideas.

**Comment by alexzaganelli** [comment]
@all-contributors please add @creazy231 for code, design and ideas.

**Comment by creazy231** [comment]
Sounds awesome 👍 
I'll add the old functions back again with a deprecated warning on function call and create a pull request you can comment on if you have questions or want to know whats happening here and there.

**Comment by creazy231** [comment]
@alexzaganelli just want to let you know that there is no way around removing this line in my opinion:

https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/services/email.js#L8

Reason: This line of code breaks http://localhost:1337/ (and maybe something else) because it prevents rendering html templates using `<%= variable %>` syntax. Strapi crashes with error 500 and a log by lodash.

⚠️ Removing this line will break email templating using `{{ variable }}`.

So what do you think? Otherwise I couldn't make this plugin work using Strapi 3.5.1

**Comment by creazy231** [comment]
also have a working import / export function for templates in my fork 👍

**Comment by alexzaganelli** [comment]
> @alexzaganelli just want to let you know that there is no way around removing this line in my opinion:
> 
> 
> 
> https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/services/email.js#L8
> 
> 
> 
> Reason: This line of code breaks http://localhost:1337/ (and maybe something else) because it prevents rendering html templates using `<%= variable %>` syntax. Strapi crashes with error 500 and a log by lodash.
> 
> 
> 
> ⚠️ Removing this line will break email templating using `{{ variable }}`.
> 
> 
> 
> So what do you think? Otherwise I couldn't make this plugin work using Strapi 3.5.1

Thank you @creazy231, I would say let's proceed removing the line https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/services/email.js#L8

**Comment by creazy231** [comment]
Yea, sounds nice to me. I'll add back old functions as I mentioned and open up a pull request tomorrow 🚀

**Comment by creazy231** [comment]
🚀  PR: https://github.com/alexzaganelli/strapi-plugin-email-designer/pull/18
feel free to comment :)

**Comment by alexzaganelli** [comment]
Hi @creazy231 

Thank you again for your contribution. I've merged the PR #18 and had to do some adjustments. Concerning about this I'd inform you that the lines 
https://github.com/creazy231/strapi-plugin-email-designer/blob/afcde3a877560d6be47b3aca07294572fdf3c106/admin/src/containers/HomePage/index.js#L205

and

https://github.com/creazy231/strapi-plugin-email-designer/blob/afcde3a877560d6be47b3aca07294572fdf3c106/admin/src/containers/HomePage/index.js#L217

wouldn't works on Mongo in which the id fields are strings.

For any other question we can use the [Discussions](https://github.com/alexzaganelli/strapi-plugin-email-designer/discussions).

Have a nice day,
Alex

**Comment by creazy231** [comment]
Hey @alexzaganelli 

Thanks for the merge and also thanks for the adjustments. Didn't use Mongo before.
I'll see what I can do to improve this awesome plugin in the future :)

Best Regards,
Tobi
