### ISSUE TITLE
Subject field

### ISSUE THREAD

**Issue by tbanys** [alexzaganelli/strapi-plugin-email-designer#20]
I would really appreciate if email designer plugin would have addition subject text field along side name and body.

**Comment by creazy231** [comment]
Already thought about and should be easy to implement.
When I find some time I'll create a PR for that feature.

**Comment by alexzaganelli** [comment]
Hi @tbanys 

I've just added the [feature](https://github.com/alexzaganelli/strapi-plugin-email-designer/commit/403fa70dcece7a302f8028207eb66a91c00c6832) you've requested.

Please let us know if it works for you.
