### ISSUE TITLE
Unable to delete and duplicate a template

### ISSUE THREAD

**Issue by VivianSolide** [alexzaganelli/strapi-plugin-email-designer#22]
Hi there,

Thank you so much for this plugin!
Nevertheless, I stumbled upon this issue:
![image](https://user-images.githubusercontent.com/9358572/111445219-7ad37300-870b-11eb-9d25-d4f84cde11fd.png)

I'm unable to delete or even duplicate a template.
And the console is empty.

Cheers,

**Comment by creazy231** [comment]
Hey Vivian,
thanks for reporting this issue. For now you can duplicate or delete your templates using `EmailTemplates` in your Collection Types. As an alternative you can use my fork at https://github.com/creazy231/strapi-plugin-email-designer of you don't use Mongo.

@alexzaganelli maybe we could use `typeof deleteConfirmationModal === 'number'` here https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/admin/src/containers/HomePage/index.js#L216 and set the id like `setDeleteConfirmationModal(+data.id)` here https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/admin/src/containers/HomePage/index.js#L277 to make it work using Mongo?

**Comment by VivianSolide** [comment]
Thanks for your answer.
I will manage to do it.

Cheers,
:beer:

**Comment by alexzaganelli** [comment]
> Hi there,
> 
> Thank you so much for this plugin!
> Nevertheless, I stumbled upon this issue:
> ![image](https://user-images.githubusercontent.com/9358572/111445219-7ad37300-870b-11eb-9d25-d4f84cde11fd.png)
> 
> I'm unable to delete or even duplicate a template.
> And the console is empty.
> 
> Cheers,

Hi @VivianSolide thank you for interesting.
I've fixed this issue. Would be great if you can upgrade the email-designer and tell us if it now works.


> Hey Vivian,
> thanks for reporting this issue. For now you can duplicate or delete your templates using `EmailTemplates` in your Collection Types. As an alternative you can use my fork at https://github.com/creazy231/strapi-plugin-email-designer of you don't use Mongo.
> 
> @alexzaganelli maybe we could use `typeof deleteConfirmationModal === 'number'` here https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/admin/src/containers/HomePage/index.js#L216 and set the id like `setDeleteConfirmationModal(+data.id)` here https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/admin/src/containers/HomePage/index.js#L277 to make it work using Mongo?

Thank you @creazy231, we cannot use `typeof deleteConfirmationModal === 'number'` due in MongoDB the id is a string type. What I've actually done is check if `!isNil(deleteConfirmationModal) && deleteConfirmationModal !== false`. Should now work in both scenarios.

**Comment by VivianSolide** [comment]
Hello @alexzaganelli 

It works!
Thank you :+1:

**Comment by creazy231** [comment]
> > Hi there,
> > Thank you so much for this plugin!
> > Nevertheless, I stumbled upon this issue:
> > ![image](https://user-images.githubusercontent.com/9358572/111445219-7ad37300-870b-11eb-9d25-d4f84cde11fd.png)
> > I'm unable to delete or even duplicate a template.
> > And the console is empty.
> > Cheers,
> 
> Hi @VivianSolide thank you for interesting.
> I've fixed this issue. Would be great if you can upgrade the email-designer and tell us if it now works.
> 
> > Hey Vivian,
> > thanks for reporting this issue. For now you can duplicate or delete your templates using `EmailTemplates` in your Collection Types. As an alternative you can use my fork at https://github.com/creazy231/strapi-plugin-email-designer of you don't use Mongo.
> > @alexzaganelli maybe we could use `typeof deleteConfirmationModal === 'number'` here https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/admin/src/containers/HomePage/index.js#L216 and set the id like `setDeleteConfirmationModal(+data.id)` here https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/admin/src/containers/HomePage/index.js#L277 to make it work using Mongo?
> 
> Thank you @creazy231, we cannot use `typeof deleteConfirmationModal === 'number'` due in MongoDB the id is a string type. What I've actually done is check if `!isNil(deleteConfirmationModal) && deleteConfirmationModal !== false`. Should now work in both scenarios.

Awesome, and a nice fix 👍
