### ISSUE TITLE
Query templates by name

### ISSUE THREAD

**Issue by TasosBak** [alexzaganelli/strapi-plugin-email-designer#23]
Hello everybody and congratulations on the great work you are doing :)

The issue is that I am trying to get a certain template by its name and not the id and I can't get it to work. I am doing it like this: http://localhost:1337/email-designer/templates?name=Table where Table is the name of the template but I am still getting the array of the templates. 

How could I go about implementing this?

**Comment by tbanys** [comment]
Hi, @TasosBak 

As I can see the endpoint which you are calling is not accepting any params, You can see it here: https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/controllers/designer.js#L30

In the meantime you can write your own endpoint and query to fetch template by name.
This is an example of query:

```js
const template = await strapi.query('email-template', 'email-designer').findOne({ name: emailTemplateName });
```

**Comment by alexzaganelli** [comment]
> Hello everybody and congratulations on the great work you are doing :)
> 
> The issue is that I am trying to get a certain template by its name and not the id and I can't get it to work. I am doing it like this: http://localhost:1337/email-designer/templates?name=Table where Table is the name of the template but I am still getting the array of the templates.
> 
> How could I go about implementing this?

Hi @TasosBak have you already tried this in your code:

```javascript
// ...

await strapi.plugins['email-designer'].services.template.fetch({ name: 'YOUR_TEMPLATE_NAME' })

// ...
```
