### ISSUE TITLE
template_id error with sendgrid

### ISSUE THREAD

**Issue by linjohnjohn** [alexzaganelli/strapi-plugin-email-designer#28]
Hello!

I was playing around with this plugin along with sendgrid as the email provider and I ran into this issue 

![image](https://user-images.githubusercontent.com/31906884/113942513-e66ea480-97ce-11eb-9c98-7d1cdd734d18.png)

This is the code/endpoint that I am testing

```js
    testEmail: async (ctx) => {
        try {
            await strapi.plugins['email-designer'].services.email.sendTemplatedEmail(
              {
                to: 'jlin@bespoke.house', // required
                from: 'team@mail.bespoke.house', // optional if /config/plugins.js -> email.settings.defaultFrom is set
                replyTo: 'team@mail.bespoke.house', // optional if /config/plugins.js -> email.settings.defaultReplyTo is set
              },
              {
                templateId: 6, // required - you can get the template id from the admin panel
                subject: `Welcome to My Project`, // If provided here will override the template's subject. Can include variables like `Welcome to <%= project_name %>`
              },
              {
                // this object must include all variables you're using in your email template
                project_name: 'Test Mailer',
              }
            );

          } catch (err) {
            strapi.log.debug('📺: ', err);
            return ctx.badRequest(null, err);
          }
          
          return "Success!"
    }
```

I believe this issue might be related to sendgrid supporting a templating feature as well along with the fact that the templateId is being passed along here: https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/df99b1a5fd35c580b57980fa917a500d6652fd11/services/email.js#L63

If passing this templateId is not strictly required on that line then perhaps removing it might be the quickest solution? Please correct me if I am wrong but I don't see why the email provider would need to know anything about what the templateId is.

Thank you! Keep up the awesome work!

**Comment by BeanSampa** [comment]
Sorry to post if I'm breaking any rules.
I am an old man of old technologies, so Github, Node and STRAPI are new to me.
I got success using a NODEMAILER provider.
But, I did the changes below in /services/emails.js
Should I do this? I really do not know.
I just want to help (and try to resolve my demand).

```
// (excluded) return strapi.plugins.email.provider.send({ ...emailOptions, ...templatedAttributes });

  return strapi.plugins['email'].services.email.send({
    to: emailOptions.to,
    subject: templatedAttributes.subject,
    text: templatedAttributes.text,
    html: templatedAttributes.html,
  });
```

**Comment by linjohnjohn** [comment]
@BeanSampa I think that would work with the sendgrid provider since templateId is no longer being passed along.

The fix I actually did on a local fork was removing requiredAttributes from this array

https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/df99b1a5fd35c580b57980fa917a500d6652fd11/services/email.js#L32

**Comment by ashmore11** [comment]
I'm also running into this issue. Trying to avoid having to fork the repo.

@linjohnjohn Did you find a fix or maybe you could submit a PR with your forked fix?

**Comment by linjohnjohn** [comment]
@ashmore11 Yes I was able to fix this by removing ...requiredAttributes from the line mentioned above.

I held off on submitting any PR as I'm not sure how "legit" this fix is--maybe requiredAttributes will contain something in the future that actually needs to be included within the attributes array

**Comment by ashmore11** [comment]
Thanks for the response @linjohnjohn!

I managed to avoid forking but just creating a new file in my app and pasting in the entire `strapi-plugin-email-designer/services/email.js` and just updating it like you mentioned. Works like a charm :)

**Comment by alexzaganelli** [comment]
Hi guys,

I hope to have a bunch of time during the weekend to face this boring incompatibility w/ SendGrid.
You'll notified by GitHub when/if I'll be able to push the fix.

Have a great time.

**Comment by alexzaganelli** [comment]
Everything should be now fixed. Please, try the new version and reopen this issue if you find a bug 🐛
