### ISSUE TITLE
Issue with sendTemplatedEmail

### ISSUE THREAD

**Issue by tention** [alexzaganelli/strapi-plugin-email-designer#30]
Tried triggering email using sendTemplatedEmail with the following codes but encountered Bad Request 400 error, and the weird part is there was no error message returned. Using v0.4.1.

```
        try {
            await strapi.plugins['email-designer'].services.email.sendTemplatedEmail(
              {
                to: user.email, // required
                from: 'no-reply@xxx.com', // optional if /config/plugins.js -> email.settings.defaultFrom is set
                replyTo: 'no-reply@xxx.com', // optional if /config/plugins.js -> email.settings.defaultReplyTo is set
              },
              {
                templateId: 4, // required - you can get the template id from the admin panel
                subject: 'Welcome'
              },
              {
                // this object must include all variables you're using in your email template
                project_name: 'Test Mailer',
              }
            );

          } catch (err) {
            strapi.log.debug('📺: ', err);
            return ctx.badRequest(null, err);
          }
```

This is the debug error from Strapi, which is an empty error.

```
[2021-05-14T07:51:27.462Z] debug �📺:  
[2021-05-14T07:51:27.464Z] debug POST /auth/local/register (11297 ms) 400
```

The response from API call is empty as well.
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": {},
  "data": {}
}
```

Sending email using the old API works but flagged as depreciated.

```
      await strapi.plugins['email-designer'].services.email.send({
        templateId,
        to,
        from,
        replyTo,
        // subject,
        data: userData,
      });
```

Couldn't verify whether it's related to the template_id faced by Sendgrid.

**Comment by tention** [comment]
I was doing some debug just now and got it working. Error seems to be caused by Heading in the template.

I have the following in a HEADING widget in the email designer.
```
Type: <%=type%>
```

However it failed when passing through the following function, so I have added _console.log(emailTemplate);_ before the following code.
```
const templatedAttributes = attributes.reduce(
    (compiled, attribute) =>
      emailTemplate[attribute]
        ? Object.assign(compiled, { [attribute]: _.template(emailTemplate[attribute])(data) })
        : compiled,
    {}
  );
```

For the console output of emailTemplate.text, instead of getting <%=type%>, it's showing as <%=TYPE%>. This is causing the reference variable to be missing from my input.

I will be getting the following error if I change my input to "TYPE".
```
[2021-05-16T07:18:57.879Z] error ReferenceError: type is not defined
```

Tried again with by putting both "TYPE" and "type" as input and it works!
```
      await strapi.plugins['email-designer'].services.email.sendTemplatedEmail(
        {
          to: result.created_by.email,
          from: 'no-reply@xxx.com', // optional if /config/plugins.js -> email.settings.defaultFrom is set
          replyTo: 'no-reply@xxx.com', // optional if /config/plugins.js -> email.settings.defaultReplyTo is set
        },
        {
          templateId: 13, // required - you can get the template id from the admin panel
          subject: 'Testing', // If provided here will override the template's subject. Can include variables like `Welcome to <%= project_name %>`
        },
        {
          TYPE: type,
          type: type,
        }
      );
```

**Comment by creazy231** [comment]
Hey @tention, could you give it a try using `<%= type %>` in your template (with the spaces) and see if it works? Documented here https://lodash.com/docs/4.17.15#template using this exact syntax should make it work and also does it for me.

**Comment by tention** [comment]
I tried that, but unfortunately it doesn't work.

![Capture](https://user-images.githubusercontent.com/16015050/118744481-fe821b00-b886-11eb-9374-ebd97b973777.PNG)

![Capture2](https://user-images.githubusercontent.com/16015050/118744488-017d0b80-b887-11eb-9456-e23a5245e379.PNG)

Will be getting following error if I do not provide both the variables, one in full uppercase.

```
{
  "errors": [
    {
      "message": "Bad Request",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "forgotPassword"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": 400,
          "data": {
            "statusCode": 400,
            "error": "Bad Request",
            "message": {},
            "data": {}
          },
          "stacktrace": [
            "Error: Bad Request",
            "    at checkBadRequest (C:\\Users\\ytee\\Project\\strapi\\my-project\\node_modules\\strapi-plugin-users-permissions\\config\\schema.graphql.js:13:23)",
            "    at resolver (C:\\Users\\ytee\\Project\\strapi\\my-project\\node_modules\\strapi-plugin-users-permissions\\config\\schema.graphql.js:233:11)"
          ]
        }
      }
    }
  ],
  "data": {
    "forgotPassword": null
  }
}
```

**Comment by creazy231** [comment]
The only thing I could imagine at this point is, that the string is set to uppercase in the builder itself and therefore renders the html and text as uppercase variables. Could you give it a check please? You could also see the output as html and text inside the database. Are your variables stored as uppercase there?

**Comment by tention** [comment]
Here's the snippet from the design jsonb column.

```
                        "contents": [
                            {
                                "type": "heading",
                                "values": {
                                    "text": "&lt;%= validationCode %&gt;",
                                    "_meta": {
                                        "htmlID": "u_content_heading_1",
                                        "htmlClassNames": "u_content_heading"
                                    },
                                    "color": "#e76467",
                                    "fontSize": "54px",
                                    "hideable": true,
                                    "_override": {
                                        "mobile": {
                                            "fontSize": "40px"
                                        }
                                    },
```

And here's the one from bodyHtml.

```
  <h1 class="v-font-size" style="margin: 0px; color: #e76467; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: arial,helvetica,sans-serif; font-size: 54px;">
    &lt;%= validationCode %&gt;
  </h1>
```

Both looks normal to me, without uppercase.

**Comment by TasosBak** [comment]
Hello guys! Where is the following code supposed to be added?
`  try {
    await strapi.plugins['email-designer'].services.email.sendTemplatedEmail(
      {
        to: 'to@example.com', // required
        from: 'from@example.com', // optional if /config/plugins.js -> email.settings.defaultFrom is set
        replyTo: 'reply@example.com', // optional if /config/plugins.js -> email.settings.defaultReplyTo is set
      },
      {
        templateId: 1, // required - you can get the template id from the admin panel
        subject: `Welcome to My Project`, // If provided here will override the template's subject. Can include variables like `Welcome to <%= project_name %>`
      },
      {
        // this object must include all variables you're using in your email template
        project_name: 'My Project',
      }
    );
  } catch (err) {
    strapi.log.debug('📺: ', err);
    return ctx.badRequest(null, err);
  }` 

I tried it in admin/src/container/HomePage/index.js inside a sendEmailTemplatesHandler async function and I get the following error: 
![image](https://user-images.githubusercontent.com/15340410/119848478-84036c00-bf14-11eb-89ba-97b768ae6447.png)

**Comment by creazy231** [comment]
> Hello guys! Where is the following code supposed to be added?
> 
> ```
> {
>   // ...
> 
>   try {
>     await strapi.plugins['email-designer'].services.email.sendTemplatedEmail(
>       {
>         to: 'to@example.com', // required
>         from: 'from@example.com', // optional if /config/plugins.js -> email.settings.defaultFrom is set
>         replyTo: 'reply@example.com', // optional if /config/plugins.js -> email.settings.defaultReplyTo is set
>       },
>       {
>         templateId: 1, // required - you can get the template id from the admin panel
>         subject: `Welcome to My Project`, // If provided here will override the template's subject. Can include variables like `Welcome to <%= project_name %>`
>       },
>       {
>         // this object must include all variables you're using in your email template
>         project_name: 'My Project',
>       }
>     );
>   } catch (err) {
>     strapi.log.debug('📺: ', err);
>     return ctx.badRequest(null, err);
>   }
> 
>   // ...
> }
> ```
> 
> I tried it in admin/src/container/HomePage/index.js inside a sendEmailTemplatesHandler async function and I get the following error:
> ![image](https://user-images.githubusercontent.com/15340410/119848478-84036c00-bf14-11eb-89ba-97b768ae6447.png)

You can use this code everywhere in your custom code. For example: `strapi/api/**/controllers/**.js`.

**Comment by TasosBak** [comment]
Thank you very much! I will look into it!
