### ISSUE TITLE
Github star says it only shows on development but i see it in production

### ISSUE THREAD

**Issue by pitops** [alexzaganelli/strapi-plugin-email-designer#32]
![Screenshot 2021-06-06 at 9 57 39 PM](https://user-images.githubusercontent.com/9624361/120936759-3657e200-c712-11eb-8f9b-054519e32fa1.png)

When you hover the X button it says that is only shows in dev env, but i am seeing it on my production build

**Comment by alexzaganelli** [comment]
Thank you @pitops 
I've fixed the issue and after the tests I'll publish the new release soon.
