### ISSUE TITLE
The templates are not committed in source code?

### ISSUE THREAD

**Issue by pitops** [alexzaganelli/strapi-plugin-email-designer#33]
Email designer is a really nice plugin, however, I would expect that when I saved a template it would commit it alongside the source code. Am I missing something?

**Comment by alexzaganelli** [comment]
Can you please explain with some example? I can't get the point.

**Comment by pitops** [comment]
So, imagine i create the templates on development env. How can i have them on production automatically?

**Comment by alexzaganelli** [comment]
Umh, the templates are not supposed to be hardcoded 🤔. Anyway you can export them from development environment to then import them in production env.

**Comment by pitops** [comment]
Can you explain to me why they are not supposed to be hardcoded?

**Comment by alexzaganelli** [comment]
Normally the informations are saved in a DB, like the users, products (for an ecommerce), comments, settings, etc etc.

If you prefer you can get the code generated by the plugin and save it in your controllers/services files.
Anyway, feel free to develop this functionality based on your idea and make a PR in the dev branch.
