### ISSUE TITLE
Can we insert dynamic content?

### ISSUE THREAD

**Issue by pitops** [alexzaganelli/strapi-plugin-email-designer#35]
I am trying to create an eshop, which means i need to send the order summary by email. Is it possible to pass a variable (e.g an array of items) and display them in a table somehow?

**Comment by creazy231** [comment]
> I am trying to create an eshop, which means i need to send the order summary by email. Is it possible to pass a variable (e.g an array of items) and display them in a table somehow?

Did you take a look into the README.md? You can use variables, yes.

**Comment by pitops** [comment]
I did and i did make use of variables however, i had to build the whole html design manually for the dynamic variable part because its an array of things and not a single value. So it kind of defeats the purpose of using an email designer if half of my html is in the template and half of it is in the code.

Would be nice if there was a way to loop through items and dynamically build a design from within the email designer

**Comment by alexzaganelli** [comment]
The README file say that the plugin use the [lodash templating language](https://lodash.com/docs/4.17.15#template). Have you looked at that? 
Actually I don't have the time to do a test but I guess you can do something like this in the body of the template:

```javascript
<% _.forEach(productsInOrder, function(product) { %>
	<li><%- product.name %></li> 
	<li><%- ... %></li> 
<% }); %> 
```

I hope this is helpful for you
