### ISSUE TITLE
Error interpolating variables inside headings

### ISSUE THREAD

**Issue by GuilleAngulo** [alexzaganelli/strapi-plugin-email-designer#36]
Hey, first of all thanks for creating this awesome plugin! 😃 

### Description
When adding a variable at `data` object param (in `sendTemplatedEmail`), and used in the template inside a `heading` tag, lodash throws a _ReferenceError_. I think this is happening because the `htmlToText` function parses headings to uppercase, creating a mismatch when interpolating.

For example, using a variable `total` inside the data param: 

|At the template                    |At the parsed `bodyText `
| ---------------------------------- | ---------------------------------- |
|  ![shot_210610_182016](https://user-images.githubusercontent.com/50624358/121598878-a9b26a00-ca18-11eb-9e31-37e8e5ae0c92.png) | ![shot_210610_173236](https://user-images.githubusercontent.com/50624358/121593457-59d0a480-ca12-11eb-84c4-6b6d0db59e26.png) |

![error](https://user-images.githubusercontent.com/50624358/121593301-2261f800-ca12-11eb-9762-21e71bbf6d3e.png)

Opened a possible solution at #37

**Comment by alexzaganelli** [comment]
Thank you for have found the bug and provided the fix @GuilleAngulo !!
LGTM, I really appreciate

**Comment by alexzaganelli** [comment]
@all-contributors please add @GuilleAngulo for bug, code.

**Comment by GuilleAngulo** [comment]
Yay! happy it was useful!
