### ISSUE TITLE
Not everything is emails in the `emailOptions`

### ISSUE THREAD

**Issue by xcivit** [alexzaganelli/strapi-plugin-email-designer#39]
To attach files to emails, you need to pass them in the `emailOptions` variables under the key `attachments` variable and assign a list of objects to it.
https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/090b414b6b695bf5d839066008e4debc1d2b2853/services/email.js#L21-L29
Possible solution:
Skip the validation for the attachment key:
```js
if(key !== "attachments") {
...
}
```

**Comment by alexzaganelli** [comment]
Thank you very much @xcivit for your contribution!

@all-contributors please add @xcivit for bug.
