### ISSUE TITLE
Problems with Strapi 3.6.3

### ISSUE THREAD

**Issue by xsliii** [alexzaganelli/strapi-plugin-email-designer#42]
First of all, great work!

We tried to get this awesome plugin work with our strapi 3.6.3  version but on run up, the following error occured.

This would be so awesome, I can help somehow to get this fixed :)

Thank you!!

#12 1.155 > strapi build                                                                                                                                                              
#12 1.155                                                                                                                                                                             
#12 2.149 Building your admin UI with development configuration ...
#12 3.257 ℹ Compiling Webpack
#12 10.79 Error: Module not found: Error: Can't resolve '../../../../helpers/coreTemplateHelper' in '/srv/app/.cache/plugins/strapi-plugin-email-designer/admin/src/containers/Designer'
#12 10.79     at /srv/app/node_modules/strapi-admin/index.js:71:23
#12 10.79     at finalCallback (/srv/app/node_modules/webpack/lib/Compiler.js:257:39)
#12 10.79     at onCompiled (/srv/app/node_modules/webpack/lib/Compiler.js:265:20)
#12 10.79     at /srv/app/node_modules/webpack/lib/Compiler.js:670:21
#12 10.79     at eval (eval at create (/srv/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
#12 10.79     at /srv/app/node_modules/webpack/lib/Compilation.js:1173:13
#12 10.79     at /srv/app/node_modules/webpack/lib/Compilation.js:1096:25
#12 10.79     at /srv/app/node_modules/webpack/lib/Compilation.js:1017:13
#12 10.79     at /srv/app/node_modules/neo-async/async.js:2830:7
#12 10.79     at /srv/app/node_modules/neo-async/async.js:2830:7
#12 10.79     at done (/srv/app/node_modules/neo-async/async.js:2863:11)
#12 10.79     at /srv/app/node_modules/neo-async/async.js:2818:7
#12 10.79     at /srv/app/node_modules/webpack/lib/Compilation.js:1017:13
#12 10.79     at /srv/app/node_modules/neo-async/async.js:2830:7
#12 10.79     at /srv/app/node_modules/neo-async/async.js:2830:7
#12 10.79     at done (/srv/app/node_modules/neo-async/async.js:2863:11)
#12 10.84 npm ERR! code ELIFECYCLE
#12 10.84 npm ERR! errno 1
#12 10.84 npm ERR! app@0.1.0 build: `strapi build`
#12 10.84 npm ERR! Exit status 1
#12 10.84 npm ERR! 
#12 10.84 npm ERR! Failed at the app@0.1.0 build script.
#12 10.84 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#12 10.89 
#12 10.89 npm ERR! A complete log of this run can be found in:
#12 10.89 npm ERR!     /root/.npm/_logs/2021-06-21T19_58_18_696Z-debug.log
------

**Comment by alexzaganelli** [comment]
I'm so sorry @xsliii
Please try to upgrade to the last 1.1.2 version and let me know. Thank you!

**Comment by xsliii** [comment]
works like a charm, thanks!
