### ISSUE TITLE
Issues with Strapi welcome page templating with plugin versions >1.0.0

### ISSUE THREAD

**Issue by dappiu** [alexzaganelli/strapi-plugin-email-designer#43]
Hi there, first of all thanks for this wonderful plugin.

I'd like to report a strange behaviour I noticed about Strapi welcome page (the one on `/` route) when I upgraded the plugin from version 1.0.0 to version 1.2.1 (but I can confirm that also 1.0.1 and 1.1.1 are affected).

Removing the plugin is enough to get rid of the problem. I was initially thinking to the modification of the templating tags to `{{ }}` which happened on 1.2.1, but then I tested also versions before and the problem is always there down to 1.0.1.

Please see the ticket I opened on Strapi repo before understanding that the problem was rather related with this plugin: https://github.com/strapi/strapi/issues/10533

Thanks

**Comment by alexzaganelli** [comment]
Hi @dappiu, (piacere di conoscerti)

I'm very happy you like the plugin!! The default Strapi Welcome page use the lodash's templating and, as you said, the new setting may had interfered with Strapi. Now it should be fixed on 🔖 1.1.3.

Please, let me know if you still meet strange behaviors.
Thank you

**Comment by dappiu** [comment]
I can confirm the issue is solved in 1.1.3, I am closing this bug with a big Thank You for the quick intervention.
(il piacere è anche mio :)
