### ISSUE TITLE
Specify sender's name using the syntax "FirstName LastName <email@example.com>"

### ISSUE THREAD

**Issue by jpizzle34** [alexzaganelli/strapi-plugin-email-designer#45]
Hi All,

I am trying to send an email so that the recipient sees a human-friendly string (that I can specify dynamically), which accompanies the email address, e.g. it could be the sender's full name. However, I get an error when I use the following syntax:

```Jane Citizen <jane.citizen@example.com>```

Note: This syntax works when I send a test email from the Strapi Email Plugin Admin UI. Also, when I send an email specifying just the email address, this plugin works fine.

How do I use the syntax described above with this plugin?

Here is a code snippet of how I am calling the `sendTemplatedEmail()`:

```
// Send booking confirmation
  const sent = await strapi.plugins[
    "email-designer"
  ].services.email.sendTemplatedEmail(
    {
      to: booking.booker.email,
      from: `${location.name} <${location.email}>`,
      replyTo: `${location.name} <${location.email}>`,
    },
    {
      templateId: process.env.CONFIRMATION_EMAIL_TEMPLATE_ID,
    },
    {
      customer: customer,
      location: _.pick(initBooking.location, ["name", "phone", "email"]),
      booking: confirmedBooking,
    }
  );
```

NODE_VERSION: v14.16.0
strapi: 3.6.2
strapi-plugin-email-designer: 1.1.3
strapi-plugin-email: ^3.6.3
strapi-provider-email-amazon-ses: ^3.6.3

UPDATE: I've created a PR related to this issue here: https://github.com/alexzaganelli/strapi-plugin-email-designer/pull/46#issue-696953701

**Comment by jpizzle34** [comment]
Looking closer at https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/92e1a0fa01ae70d402f67098238b788341726dcc/services/email.js#L8-L9

It seems like the regex test fails if '<' '>' are included.

Also is this regex test necessary? Isn't the email validation carried out by the underlying strapi email provider?

Let me know what you guys think?

**Comment by alexzaganelli** [comment]
Thank you for your great contributions @jpizzle34 on #46 !!

@all-contributors please add @jpizzle34 for enhancements.

**Comment by alexzaganelli** [comment]
Thank you for your great contributions @jpizzle34 on #46 !!

@all-contributors please add @jpizzle34 for code.
