### ISSUE TITLE
[Bug]: Importing Templates Changes TemplateId

### ISSUE THREAD

**Issue by meck93** [alexzaganelli/strapi-plugin-email-designer#50]
## Description
I have created a few templates using the local development environment. Adjusted the email code according to fetch the respective template via its `templateId`. Everything works great 🎉 Btw. thanks for the great work! 

I exported the templates and tried to import them into our staging environment. But the problem is that the `id` of the template stored in the JSON file is used to create the `templateId` during the import. If the `id` already exists in the database, the `templateId` changes during the import and, therefore, the old `templateId` used in the code to fetch the template is no longer correct.

## Solution Proposal
We should differentiate between the `templateId` and the `id` of the template in the database table. Both must be unqiue but the `templateId` provided via the `id` field in the JSON file should never change (on import). The import should rather fail if a template with a given `templateId` already exists. The goal of this is that the `templateId` can be used in the code to retrieve the template without worrying that it might change during a template import. 

I hope I was able to explain what the problem is. If not, please let me know, I will elaborate further...

**Comment by alexzaganelli** [comment]
Hi @meck93 , thank you a lot for your contribution and sorry for the delay. I'm abroad on holiday and there isn't the internet connection.

BTW As far as I can test, I see some little errors on your commit. For example:

- the new templateId's HTML input tag is too narrow therefore it's not possible to read the entire placeholder
- it's not a number input type therefore you can put char values. If you do that you'll see no changes but you receive an error from the backend

I hope you can fix that, otherwise I'll do that as soon as I return home.
Thank you in advance

**Comment by meck93** [comment]
> Hi @meck93 , thank you a lot for your contribution and sorry for the delay. I'm abroad on holiday and there isn't the internet connection.
> 
No worries at all. I didn't expect a fast response. Enjoy your holidays and some time offline 👍 

> BTW As far as I can test, I see some little errors on your commit. For example:
> 
> * the new templateId's HTML input tag is too narrow therefore it's not possible to read the entire placeholder
I will fix this!
- either make the box larger (but the input will seldomly be larger than 5-10 numbers, right? 
- or, make the placeholder text a shorter? 

> * it's not a number input type therefore you can put char values. If you do that you'll see no changes but you receive an error from the backend
I will fix this as well!

> * can more templates have the same sourceTemplateId value? I see no check about this
The `sourceCodeTemplateId` has to be unique. 
```
    "sourceCodeToTemplateId": {
      "type": "integer",
      "required": false,
      "unique": true
    }
```

Therefore, creating a new template with an existing `sourceCodeTemplateId` or modifying it to an existing value will fail. The database will return an error and it will be displayed in the frontend: https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/108598c02e38520342288cde067a014aa3362dc2/admin/src/containers/Designer/index.js#L216-L234

**Comment by meck93** [comment]
@alexzaganelli once you have tested all the changes (after your holidays, don't rush 😄). Can you make a new release i.e. publish a new version of the npm package?
