### ISSUE TITLE
I get a white screen when I go to see the public role

### ISSUE THREAD

**Issue by Husdady** [alexzaganelli/strapi-plugin-email-designer#57]
I installed your package to add a custom email template. I created a custom / contact endpoint, which sends a message to my email, when making a request to the endpoint I get a Forbidden 403, so I think the endpoint is not activated in the interface, enter roles, publish and get a white screen, is it a bug?

![image](https://user-images.githubusercontent.com/76859196/130381756-c7367c38-1d19-471b-aa05-6c6b1b75fb76.png)

**Comment by meck93** [comment]
hey @Husdady - I just realised the same. It looks like https://github.com/strapi/strapi/issues/10613 is the issue. I will open a PR to fix the issue until Strapi has fixed the issue themselves.
