### ISSUE TITLE
Cannot duplicate a template

### ISSUE THREAD

**Issue by zguig52** [alexzaganelli/strapi-plugin-email-designer#63]
Hi,

First thanks for the very good job and the quality of this project. I started to use it. I found a small issue on the latest version.

The DB column email_templates_sourceCodeToTemplateId has a unique constraint and when duplicating, the insert request is trying to insert this value, raising an error:
 warn Duplicate entry Error: insert into `email_templates` (`bodyHtml`, `bodyText`, `created_at`, `design`, `enabled`, `name`, `sourceCodeToTemplateId`, `subject`, `tags`, `updated_at`) values [...] ER_DUP_ENTRY: Duplicate entry '0' for key 'email_templates_sourceCodeToTemplateId_unique'

error Error: Duplicate entry
  at handleDatabaseError (/srv/app/node_modules/strapi-connector-bookshelf/lib/utils/errors.js:25:11)
  at Object.create (/srv/app/node_modules/strapi-connector-bookshelf/lib/queries.js:60:14)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Object.create (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:15:18)
  at async /srv/app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
  at async /srv/app/node_modules/strapi-utils/lib/policy.js:68:5
  at async /srv/app/node_modules/strapi/lib/middlewares/parser/index.js:48:23
  at async /srv/app/node_modules/strapi/lib/middlewares/xss/index.js:26:9

I have tried to remove the value I had setted here in the origin template and saved it, but it seems that it then uses a default 0 value when duplicating it.

I think this field "sourceCodeToTemplateId" shall not be part of the duplication action.

**Comment by zguig52** [comment]
To explain a bit further, this issue appears when sourceCodeToTemplateId has been set (even if removed later). When it is not, duplication is working.

**Comment by meck93** [comment]
It should be fixed by the latest release 1.1.7 and this commit https://github.com/alexzaganelli/strapi-plugin-email-designer/commit/944db7c1537d5257ff9b118a7a76d0463fc01d25
