### ISSUE TITLE
URL and TOKEN variables

### ISSUE THREAD

**Issue by PiotrAleksander** [alexzaganelli/strapi-plugin-email-designer#73]
Thanks for creating this designer plugin.
I've added a button to Set Password core template with the following:
`<%= URL %>?code=<%= TOKEN %>`
(it's taken from the original template). I've also tried lodash syntax:
`{{URL}}?code={{TOKEN}}`
but it does not work (URL and TOKEN are empty strings on the inbox side). 
Though the first version used as an URL for an <a> tag works as expected.
Is it an issue with Unlayer button or am I missing something?

This does not work:
![image](https://user-images.githubusercontent.com/6314591/147443491-bfaf7781-bca8-41c0-9626-78d51163559b.png)
![image](https://user-images.githubusercontent.com/6314591/147443545-0f96e178-1dac-4b90-917a-a4ff52ffdd5a.png)

This works:
![image](https://user-images.githubusercontent.com/6314591/147443570-caecc48a-a50d-42e1-976b-f921c900e82a.png)

**Comment by alexzaganelli** [comment]
Hi @PiotrAleksander 

I think the best solution could be to style a div giving to it the aspect of a button. I fear that the Button component from Unlayer encode the string, breaking the URL.

**Comment by alexzaganelli** [comment]
> Thanks for creating this designer plugin. I've added a button to Set Password core template with the following: `<%= URL %>?code=<%= TOKEN %>` (it's taken from the original template). I've also tried lodash syntax: `{{URL}}?code={{TOKEN}}` but it does not work (URL and TOKEN are empty strings on the inbox side). Though the first version used as an URL for an tag works as expected. Is it an issue with Unlayer button or am I missing something?
> 
> This does not work: ![image](https://user-images.githubusercontent.com/6314591/147443491-bfaf7781-bca8-41c0-9626-78d51163559b.png) ![image](https://user-images.githubusercontent.com/6314591/147443545-0f96e178-1dac-4b90-917a-a4ff52ffdd5a.png)
> 
> This works: ![image](https://user-images.githubusercontent.com/6314591/147443570-caecc48a-a50d-42e1-976b-f921c900e82a.png)

BTW the correct syntax should be `{{= VAR_NAME }}` and not `{{ VAR_NAME }}`
