### ISSUE TITLE
Strapi 4 support

### ISSUE THREAD

**Issue by inovosel** [alexzaganelli/strapi-plugin-email-designer#74]
I couldn't get Email Designer running with Strapi 4. Is there a way to get it running or are there any plans for Strapi 4 support?

**Comment by creazy231** [comment]
Strapi v4 is currently not supported. I'd like to change this but I have not that much time to do so.

**Comment by alexzaganelli** [comment]
Hi guys, the new plugin for the v4 is coming. Please be patient

**Comment by alexzaganelli** [comment]
Hi guys

please follow this update:
https://github.com/alexzaganelli/strapi-plugin-email-designer/discussions/55#discussioncomment-2129484
