### ISSUE TITLE
Strapi v4, html and design variables never get filled. 

### ISSUE THREAD

**Issue by Moreno-dev** [alexzaganelli/strapi-plugin-email-designer#77]
While saving a template the html part doesn't get saved while the text part does. Analysing the React component it looks like that the variables design and html never receive their value from a function. 
V 2.0.0 Strapi V 4.0.7

**Comment by alexzaganelli** [comment]
May you please try the v2.0.1?
Thank you

**Comment by Moreno-dev** [comment]
is it already available through NPM?

**Comment by alexzaganelli** [comment]
Yes, since yesterday morning.
Please, let me known if you still have this issue.

**Comment by Moreno-dev** [comment]
> Yes, since yesterday morning. Please, let me known if you still have this issue.
Same issue, when the /new endpoint gets called it doesn't get the bodyHtml in the body of the http request.
I've been looking a bit at the react component yesterday and it looks like the two variables that should receive their value in this chunk (Designer/index.js)

    let design, html;

    try {
      emailEditorRef.current.editor.exportHtml((data) => ({ design, html } = data));
    } catch (error) {
      console.log(error);
      return;
    }

I've tried some console.log here and there and it always returns undefined for html and design

**Comment by Moreno-dev** [comment]
emailEditorRef.current.editor.exportHtml(async data => {
      const {design, html} = data
      try {
        let response;
        if (templateId) {
          response = await request(`/${pluginId}/templates/${templateId}`, {
            method: 'POST',
            body: {
              name: templateData?.name || getMessage('noName'),
              templateReferenceId: templateData?.templateReferenceId,
              subject: templateData?.subject || '',
              design,
              bodyText,
              bodyHtml: html,
            },
          });
        } else if (coreEmailType) {
          response = await request(`/${pluginId}/core/${coreEmailType}`, {
            method: 'POST',
            body: {
              subject: templateData?.subject || '',
              design,
              message: html,
              bodyText,
            },
          });
        }
  
        toggleNotification({
          type: 'success',
          message: `${pluginId}.notification.success.submit`,
        });
        togglePrompt(false);
  
        if (templateId === 'new' && templateId !== response.id)
          history.replace(`/plugins/${pluginId}/design/${response.id}`);
      } catch (err) {
        console.error(err?.response?.payload);
  
        const errorMessage = err?.response?.payload?.message;
        if (errorMessage) {
          toggleNotification({
            type: 'warning',
            title: 'Error',
            message: errorMessage,
          });
        } else {
          toggleNotification({
            type: 'warning',
            title: 'Error',
            message: `${pluginId}.notification.error`,
          });
        }
      }
    })


might be a solution to move all strapi saving logic inside the exportHtml func. At least the htm gets saved now...Still I'm not getting the auto-text function

**Comment by Moreno-dev** [comment]
Also, in the /server/services/email.js file I had to change the strapi.query() function to the new strapi way of calling a plugin i.e. plugin::users-permissions.user, or in this case plugin::email-designer.email-template otherwise it would give an error because it couldn't find the appropriate model in the DB. 

 if (templateReferenceId) {
      const response = await strapi.query("plugin::email-designer.email-template").findOne({ templateReferenceId });
      ({ bodyHtml, bodyText, subject } = response);
    } else {
      const response = await strapi.query("plugin::email-designer.email-template").findOne({ id: emailTemplate.templateId });
      ({ bodyHtml, bodyText, subject } = response);
    }

**Comment by alexzaganelli** [comment]
Thank you very much for your contribution @Moreno-dev 
Please try the v2.0.3 and if you still can't use the plugin I'd ask you to make a PR.

Ps. remember to re-build the admin with `yarn build`

**Comment by Moreno-dev** [comment]
@alexzaganelli it looks like it's working now! Good job mate!
