### ISSUE TITLE
Unable to edit Strapi's core email templates

### ISSUE THREAD

**Issue by BayBreezy** [alexzaganelli/strapi-plugin-email-designer#78]
Hey,

Thanks for rewriting this awesome plugin ❤.

When I try to load one of the core templates, I get a 400 response. Here is the endpoint logged:
http: GET /email-designer/core/user-address-confirmation (27 ms) 400

When the page gets loaded, it is an empty template.

After creating a design, clicking on the "Save design" triggers no action. Nothing happens.

Is there something that I need to change in my settings? What am I missing?

**Comment by alexzaganelli** [comment]
Hi @BayBreezy thank you for your contribution.
May you please try the new v2.0.4 an try again?

Ps. there was a typo on a variable's name. This [commit](https://github.com/alexzaganelli/strapi-plugin-email-designer/commit/45ec6f65e01d3e532d836d3d1b08d5999269ff66) should fix it.
