### ISSUE TITLE
[Strapi V4] Cant add custom fonts to the template

### ISSUE THREAD

**Issue by Flowko** [alexzaganelli/strapi-plugin-email-designer#80]
**Issue:**
the fonts list doesnt seem to show any fonts, even after i updated the config, ive rebuilt strapi again but with no luck
![image](https://user-images.githubusercontent.com/35883748/153708552-5f479f77-8665-4272-8258-bd6194ae0b40.png)
![image](https://user-images.githubusercontent.com/35883748/153708581-d2e10404-5864-4894-817e-b040bca3c7af.png)

**my config:**
its the same one provided in Read.me
```
'email-designer': {
    editor: {
      tools: {
        heading: {
          properties: {
            text: {
              value: 'This is the new default text!'
            }
          }
        }
      },
      options: {
        features: {
          colorPicker: {
            presets: ['#D9E3F0', '#F47373', '#697689', '#37D67A']
          }
        },
        fonts: {
          showDefaultFonts: true,
          customFonts: [
            {
              label: "Anton",
              value: "'Anton', sans-serif",
              url: "https://fonts.googleapis.com/css?family=Anton",
            },
            {
              label: "Lato",
              value: "'Lato', Tahoma, Verdana, sans-serif",
              url: "https://fonts.googleapis.com/css?family=Lato",
            },
          ],
        },
        mergeTags: [
          {
            name: 'Email',
            value: '{{= USER.username }}',
            sample: 'john@doe.com',
          },
        ]
      },
      appearance: {
        theme: "dark",
        panels: {
          tools: {
            dock: 'left'
          }
        }
      }
    }
  },
```

**Comment by alexzaganelli** [comment]
Should be fixed on v2.0.5 ([9140608](https://github.com/alexzaganelli/strapi-plugin-email-designer/commit/914060835c55008c79b57ce09baa4a2c384f5e25))

**Comment by Flowko** [comment]
@alexzaganelli working now, thanks alot

**Comment by Flowko** [comment]
@alexzaganelli ah sorry to bother u, do u know how to include the fonts in the email, as it doesnt get styled when the email is sent, the text has the font familly but with no script attached to it, which makes it useless

**email template:**
![image](https://user-images.githubusercontent.com/35883748/153716244-bfb9c69f-9b14-4548-a497-615e8a60bd04.png)
**the email sent:**
![image](https://user-images.githubusercontent.com/35883748/153716261-27bc7fd0-5165-43fb-85ee-a8189bfe1701.png)
