### ISSUE TITLE
[Strapi V4] the config doesnt seem to do anything

### ISSUE THREAD

**Issue by Flowko** [alexzaganelli/strapi-plugin-email-designer#81]
ive updated some fields in the config, but it doesnt seems like its updating anything in the editor,
ive checked where the config gets called, and the request returns an empty html page instead of the config, not sure if its the cause the issue

![image](https://user-images.githubusercontent.com/35883748/153716095-68edf6d5-fbe7-4835-b449-8581127ee8df.png)

**Comment by alexzaganelli** [comment]
Please, try the v2.0.6 with the new README.

**Comment by Flowko** [comment]
its working now thanks!
