### ISSUE TITLE
[Strapi V4] Deploying Strapi 4.0.7 with this plugin version 2.0.6 gives Unsupported engine

### ISSUE THREAD

**Issue by enflam3** [alexzaganelli/strapi-plugin-email-designer#83]
Hello, first of all thanks for this amazing plugin, I already checked it out, it saves me a lot of time building mail templates.

However problem is that after making everything working on local development I cannot deploy to production.
DigitalOcean App engine works with yarn command and throws this error:

yarn add strapi-plugin-email-designer
[3/5] Fetching packages...
error strapi-utils@3.6.8: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.13.1"
error Found incompatible module.

on localhost with npm install strapi-plugin-email-designer@latest its only warning and I can build and run my project but not on production:

![image](https://user-images.githubusercontent.com/47244576/153728881-6d11b547-7f50-4e7d-aed7-7b762e412524.png)

Could you please take a look at this issue?

**Comment by alexzaganelli** [comment]
Hi @enflam3,

please use the latest release.

Run this command:

```bash
yarn add strapi-plugin-email-designer@latest

# or

npm i -S strapi-plugin-email-designer@latest
```

and let me know if it's working, thanks.

**Comment by alexzaganelli** [comment]
Please, try to install only this plug-in and then also the others one at time. 
The email-designer plug-in doesn't seem to have _strapi-utils_ as a dependency so I don't know why you get this error.

**Comment by enflam3** [comment]
yes, Iam very sorry I just found out that that was the other plugin I recently added: strapi-provider-email-gmail-2lo

**Comment by alexzaganelli** [comment]
Don't worry. Please close the issue and good code 🚀
