### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by akilshadi** [alexzaganelli/strapi-plugin-email-designer#86]
In Github it is said that templateReferenceId must be used, but two templates can have the same templateReferenceId, how can make difference between them?
ID    ReferenceId    Name
-----------------------------------------
1.    1                         Template 1 v1
2.    1                        Template 1 v2
3.    1                        Template 1 v3

how i can specify that template with id=3 and referenceId=1 and Name Template 1 v3 will be used to send the email?

**Comment by Flowko** [comment]
i see that templateId is not mentioned in the Read me.

its best to use it 
You can get the templateId by copying it from the tempaltes page
![image](https://user-images.githubusercontent.com/35883748/154088850-317fdce9-1943-4e6f-8269-3682346af573.png)

```

await strapi.plugins['email-designer'].services.email.sendTemplatedEmail(
          {
            to: email
          },
          {
            templateId: //your tempalte id,
          },
          data
          );

```

**Comment by Flowko** [comment]
ah okay i get it now
