### ISSUE TITLE
Unable to run project after installation

### ISSUE THREAD

**Issue by jonasstams** [alexzaganelli/strapi-plugin-email-designer#96]
### Describe the bug

After installation I get the following error: error: Could not load js config file /node_modules/strapi-plugin-email-designer/strapi-server.js: Unexpected token '?'
Error: Could not load js config file /node_modules/strapi-plugin-email-designer/strapi-server.js: Unexpected token '?'

### Steps to reproduce the behavior

1. yarn add strapi-plugin-email-designer
2. yarn build
3. yarn develop

### Expected behavior

Should work

**Comment by ihassansattar** [comment]
Did you manage to resolve this issue? I am getting the same error.
